variables:
  INVENIO_IMAGE_NAME: elter_dar
  INVENIO_PROJECT_PATH: .
  INVENIO_MINOR_VERSION: 3
  INVENIO_MAJOR_VERSION: 0
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: "unix:///runner/services/docker/docker.sock"

default:
  services:
    - docker:27.4.0-rc.4-dind


stages:
  - push

invenio-build-and-push:
  stage: push
  tags:
    - invenio
  image:
    name: copas-market.cerit-sc.cz/dai/builder:0.8.4-alpine
    entrypoint: [""]
  before_script:
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"${HARBOR_URL}\":{\"auth\":\"$(printf "%s:%s" "${HARBOR_USERNAME}" "${HARBOR_ROBOT_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  - cd $INVENIO_PROJECT_PATH
  script:
  - bash /utils/ci.sh $INVENIO_MINOR_VERSION $INVENIO_MAJOR_VERSION $HARBOR_URL $HARBOR_PROJECT $INVENIO_IMAGE_NAME ./Prod.Dockerfile
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    changes:
      compare_to: 'refs/heads/master~1'
      paths:
      - '**/*'

