variables:
  INVENIO_IMAGE_NAME: elter_dar
  INVENIO_PROJECT_PATH: .
  INVENIO_MINOR_VERSION: 3
  INVENIO_MAJOR_VERSION: 0

stages:
  - push

invenio-build-and-push:
  stage: push
  image:
    name: copas-market.cerit-sc.cz/dai/builder:0.6.3
    entrypoint: [""]
  before_script:
  - echo "{\"auths\":{\"${HARBOR_URL}\":{\"auth\":\"$(printf "%s:%s" "${HARBOR_USERNAME}" "${HARBOR_ROBOT_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  - cd $INVENIO_PROJECT_PATH
  script:
  - bash /utils/ci.sh $INVENIO_MINOR_VERSION $INVENIO_MAJOR_VERSION $HARBOR_URL $HARBOR_PROJECT $INVENIO_IMAGE_NAME ./Prod.Dockerfile
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    changes:
      compare_to: 'refs/heads/master~1'
      paths:
      - '**/*'

  - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
    changes:
      compare_to: 'refs/heads/master'
      paths:
      - '**/*'
